const dados = {
    "site_id": "MLB",
    "country_default_time_zone": "GMT-03:00",
    "query": "${computador}",
    "paging": {},
    "results": [
        {
            "id": "MLB1735630237",
            "title": "Notebook Multilaser Dual Core 4gb 128gb Ssd M2 - Windows 10 ",
            "condition": "new",
            "thumbnail_id": "618992-MLB44264814631_122020",
            "catalog_product_id": "MLB20359456",
            "listing_type_id": "gold_pro",
            "permalink": "https://produto.mercadolivre.com.br/MLB-1735630237-notebook-multilaser-dual-core-4gb-128gb-ssd-m2-windows-10-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1652",
            "domain_id": "MLB-NOTEBOOKS",
            "thumbnail": "http://http2.mlstatic.com/D_618992-MLB44264814631_122020-I.jpg",
            "currency_id": "BRL",
            "order_backend": 1,
            "price": 1199,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 5,
            "available_quantity": 1,
            "official_store_id": 5172,
            "official_store_name": "SLA Informatica",
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "variation_filters": [],
            "shipping": {},
            "stop_time": "2040-12-02T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "variations_data": {},
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "differential_pricing": {},
            "inventory_id": null
        },
        {
            "id": "MLB2212632547",
            "title": "Pc Escritório Intel I5 + 8gb Ram + Ssd 240 + Fonte 200w | V1",
            "condition": "new",
            "thumbnail_id": "974956-MLB49761291127_042022",
            "catalog_product_id": null,
            "listing_type_id": "gold_pro",
            "permalink": "https://produto.mercadolivre.com.br/MLB-2212632547-pc-escritorio-intel-i5-8gb-ram-ssd-240-fonte-200w-v1-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1649",
            "domain_id": "MLB-DESKTOP_COMPUTERS",
            "thumbnail": "http://http2.mlstatic.com/D_974956-MLB49761291127_042022-I.jpg",
            "currency_id": "BRL",
            "order_backend": 2,
            "price": 899.9,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 5,
            "available_quantity": 1,
            "official_store_id": null,
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2042-03-16T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "differential_pricing": {},
            "inventory_id": "VTYF05087"
        },
        {
            "id": "MLB2720099495",
            "title": "Notebook Multilaser M11w Prime Pc280 Prateada Táctil 11.6 , Intel Celeron N4020 4gb De Ram 64gb Ssd, Intel Uhd Graphics 600 1366x768px Windows 11 Home",
            "condition": "new",
            "thumbnail_id": "626936-MLA50293629492_062022",
            "catalog_product_id": "MLB19158523",
            "listing_type_id": "gold_special",
            "permalink": "https://www.mercadolivre.com.br/notebook-multilaser-m11w-prime-pc280-prateada-tactil-116-intel-celeron-n4020-4gb-de-ram-64gb-ssd-intel-uhd-graphics-600-1366x768px-windows-11-home/p/MLB19158523",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1652",
            "domain_id": "MLB-NOTEBOOKS",
            "thumbnail": "http://http2.mlstatic.com/D_626936-MLA50293629492_062022-I.jpg",
            "currency_id": "BRL",
            "order_backend": 3,
            "price": 1299.9,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 50,
            "available_quantity": 1,
            "official_store_id": null,
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2042-07-10T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": true,
            "discounts": null,
            "promotions": [
            ],
            "inventory_id": null
        },
        {
            "id": "MLB1591046018",
            "title": "Computador Concórdia I3 9100f 8gb Ddr4 Ssd 120gb",
            "condition": "new",
            "thumbnail_id": "746490-MLB52525208323_112022",
            "catalog_product_id": null,
            "listing_type_id": "gold_pro",
            "permalink": "https://produto.mercadolivre.com.br/MLB-1591046018-computador-concordia-i3-9100f-8gb-ddr4-ssd-120gb-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1649",
            "domain_id": "MLB-DESKTOP_COMPUTERS",
            "thumbnail": "http://http2.mlstatic.com/D_746490-MLB52525208323_112022-I.jpg",
            "currency_id": "BRL",
            "order_backend": 4,
            "price": 2113.25,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 25,
            "available_quantity": 1,
            "official_store_id": null,
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2040-07-06T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "differential_pricing": {},
            "inventory_id": null
        },
        {
            "id": "MLB2606668782",
            "title": "Cpu Lenovo M710q Mini Intel Core I3 7ger 8gb 240gb Promoção",
            "condition": "new",
            "thumbnail_id": "757859-MLB49597136586_042022",
            "catalog_product_id": null,
            "listing_type_id": "gold_pro",
            "permalink": "https://produto.mercadolivre.com.br/MLB-2606668782-cpu-lenovo-m710q-mini-intel-core-i3-7ger-8gb-240gb-promoco-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1649",
            "domain_id": "MLB-DESKTOP_COMPUTERS",
            "thumbnail": "http://http2.mlstatic.com/D_757859-MLB49597136586_042022-I.jpg",
            "currency_id": "BRL",
            "order_backend": 5,
            "price": 1599,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 5,
            "available_quantity": 1,
            "official_store_id": 5172,
            "official_store_name": "SLA Informatica",
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2042-04-02T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "differential_pricing": {},
            "inventory_id": null
        },
        {
            "id": "MLB2608438290",
            "title": "Computador Sff Concórdia + Monitor 21,5'' I5 8gb Ssd 480gb",
            "condition": "new",
            "thumbnail_id": "658611-MLB71926106412_092023",
            "catalog_product_id": null,
            "listing_type_id": "gold_special",
            "permalink": "https://produto.mercadolivre.com.br/MLB-2608438290-computador-sff-concordia-monitor-215-i5-8gb-ssd-480gb-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1649",
            "domain_id": "MLB-DESKTOP_COMPUTERS",
            "thumbnail": "http://http2.mlstatic.com/D_658611-MLB71926106412_092023-I.jpg",
            "currency_id": "BRL",
            "order_backend": 6,
            "price": 1653.75,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 4,
            "available_quantity": 1,
            "official_store_id": null,
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2042-04-03T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "inventory_id": null
        },
        {
            "id": "MLB2916348888",
            "title": "Notebook 2 Em 1 Positivo Duo C464d Intel® Celeron® ",
            "condition": "new",
            "thumbnail_id": "687258-MLB52271101446_112022",
            "catalog_product_id": null,
            "listing_type_id": "gold_special",
            "permalink": "https://produto.mercadolivre.com.br/MLB-2916348888-notebook-2-em-1-positivo-duo-c464d-intel-celeron-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1652",
            "domain_id": "MLB-NOTEBOOKS",
            "thumbnail": "http://http2.mlstatic.com/D_687258-MLB52271101446_112022-I.jpg",
            "currency_id": "BRL",
            "order_backend": 7,
            "price": 1549,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 50,
            "available_quantity": 1,
            "official_store_id": 4340,
            "official_store_name": "Positivo",
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "variation_filters": [],
            "shipping": {},
            "stop_time": "2042-10-29T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "variations_data": {},
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "inventory_id": null
        },
        {
            "id": "MLB2094314521",
            "title": "Pc Computador Cpu Intel Core I5 Ssd 240gb 8gb Memória Ram",
            "condition": "new",
            "thumbnail_id": "685633-MLB48317617290_112021",
            "catalog_product_id": null,
            "listing_type_id": "gold_special",
            "permalink": "https://produto.mercadolivre.com.br/MLB-2094314521-pc-computador-cpu-intel-core-i5-ssd-240gb-8gb-memoria-ram-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1649",
            "domain_id": "MLB-DESKTOP_COMPUTERS",
            "thumbnail": "http://http2.mlstatic.com/D_685633-MLB48317617290_112021-I.jpg",
            "currency_id": "BRL",
            "order_backend": 8,
            "price": 1062,
            "original_price": 1180,
            "sale_price": null,
            "sold_quantity": 5,
            "available_quantity": 1,
            "official_store_id": null,
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2041-11-18T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "inventory_id": null
        },
        {
            "id": "MLB1428585826",
            "title": "Computador Sff Monitor 19,5''dual Core 4gb Ddr3 Ssd 120gb",
            "condition": "new",
            "thumbnail_id": "601717-MLB71941291612_092023",
            "catalog_product_id": null,
            "listing_type_id": "gold_pro",
            "permalink": "https://produto.mercadolivre.com.br/MLB-1428585826-computador-sff-monitor-195dual-core-4gb-ddr3-ssd-120gb-_JM",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB1649",
            "domain_id": "MLB-DESKTOP_COMPUTERS",
            "thumbnail": "http://http2.mlstatic.com/D_601717-MLB71941291612_092023-I.jpg",
            "currency_id": "BRL",
            "order_backend": 9,
            "price": 1506.56,
            "original_price": null,
            "sale_price": null,
            "sold_quantity": 5,
            "available_quantity": 1,
            "official_store_id": null,
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2040-02-01T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": false,
            "discounts": null,
            "promotions": [
            ],
            "differential_pricing": {},
            "inventory_id": null
        },
        {
            "id": "MLB2894257396",
            "title": "Kit De Teclado + Mouse Mecânico Silencioso Abnt2 Gamer Rgb Usb Pc Luuk Young Be-700 Cor Preto",
            "condition": "new",
            "thumbnail_id": "972255-MLU70089613740_062023",
            "catalog_product_id": "MLB19731883",
            "listing_type_id": "gold_special",
            "permalink": "https://www.mercadolivre.com.br/kit-de-teclado-mouse-mecnico-silencioso-abnt2-gamer-rgb-usb-pc-luuk-young-be-700-cor-preto/p/MLB19731883",
            "buying_mode": "buy_it_now",
            "site_id": "MLB",
            "category_id": "MLB5914",
            "domain_id": "MLB-KEYBOARD_AND_MOUSE_KITS",
            "thumbnail": "http://http2.mlstatic.com/D_972255-MLU70089613740_062023-I.jpg",
            "currency_id": "BRL",
            "order_backend": 10,
            "price": 84.59,
            "original_price": 140.99,
            "sale_price": null,
            "sold_quantity": 5,
            "available_quantity": 500,
            "official_store_id": null,
            "use_thumbnail_id": true,
            "accepts_mercadopago": true,
            "tags": [],
            "shipping": {},
            "stop_time": "2042-10-21T04:00:00.000Z",
            "seller": {},
            "seller_address": {},
            "address": {},
            "attributes": [],
            "installments": {},
            "winner_item_id": null,
            "catalog_listing": true,
            "discounts": null,
            "promotions": [
            ],
            "inventory_id": null
        }]
}

module.exports = {
    dados
}